/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.afcas;

import com.afcas.AfcasApp;
import org.junit.Test;

public class AfcasAppTest {
    @Test public void appHasAGreeting() {
        AfcasApp classUnderTest = new AfcasApp();
    }
}
